name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  check_project:
    name: Rust project
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Add public keys
        run: sudo apt-get update && sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 &&
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true

#      - name: Install OpenCV
#        uses: awalsh128/cache-apt-pkgs-action@latest
#        with:
#          packages: libopencv-calib3d-dev libopencv-contrib-dev libopencv-features2d-dev libopencv-highgui-dev libopencv-imgcodecs-dev libopencv-objdetect-dev libopencv-shape-dev libopencv-stitching-dev libopencv-superres-dev libopencv-video-dev libopencv-videoio-dev libopencv-videostab-dev libopencv4.2-java libopencv-calib3d4.2 libopencv-contrib4.2 libopencv-features2d4.2 libopencv-highgui4.2 libopencv-imgcodecs4.2 libopencv-videoio4.2 libgdal26 libodbc1
#          version: 1.2.2

      - name: install OpenCV
        run: sudo apt-get install -y libopencv-dev libopencv-calib3d-dev libopencv-contrib-dev libopencv-features2d-dev libopencv-highgui-dev libopencv-imgcodecs-dev libopencv-objdetect-dev libopencv-shape-dev libopencv-stitching-dev libopencv-superres-dev libopencv-video-dev libopencv-videoio-dev libopencv-videostab-dev libopencv4.2-java libopencv-calib3d4.2 libopencv-contrib4.2 libopencv-features2d4.2 libopencv-highgui4.2 libopencv-imgcodecs4.2 libopencv-videoio4.2 libgdal26 libodbc1

      - name: Clang
        run: sudo apt-get install -y clang && sudo ln -s libclang.so.1 /usr/lib/llvm-10/lib/libclang.so

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install -y --no-install-recommends libasound2-dev libudev-dev

      - name: Install other deps
        run: sudo apt-get install -y portaudio19-dev build-essential libpulse-dev libdbus-1-dev pkg-config libx11-dev libatk1.0-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libwayland-dev libxkbcommon-dev



#
#      - name: Install OpenCV

      - name: Check project
        run: cargo check

      - name: Test project
        run: cargo test -vv
#
#  docs-rs:
#      runs-on: ubuntu-20.04
#      steps:
#        - uses: actions/checkout@v2
#
#        - name: Install Rust
#          uses: actions-rs/toolchain@v1
#          with:
#            toolchain: stable
#            default: true
#
#        - name: Run a documentation generation test
#          run: ci/docs-rs.sh
#          shell: bash
